<?php
	/**
	 * Copy-paste from Advanced Custom Fields export.
	 *
	 * @package colby-openhours
	 */

if ( function_exists( 'register_field_group' ) ) {
	register_field_group(array(
			'id' => 'acf_branch-hours',
			'title' => 'Branch Hours',
			'fields' => array(
				array(
					'key' => 'field_53c804aee03d7',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'required' => 1,
					'choices' => array(
						'Regular Hours' => 'Regular Hours',
						'Special Hours' => 'Special Hours',
						'' => '',
					),
					'default_value' => 'Special Hours',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array(
					'key' => 'field_53c807a98d26e',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_picker',
					'conditional_logic' => array(
						'status' => 1,
						'rules' => array(
							array(
								'field' => 'field_53c804aee03d7',
								'operator' => '==',
								'value' => 'Special Hours',
							),
						),
						'allorany' => 'all',
					),
					'date_format' => 'mm/dd/yy',
					'display_format' => 'mm/dd/yy',
					'first_day' => 1,
				),
				array(
					'key' => 'field_53c807cc8d26f',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_picker',
					'conditional_logic' => array(
						'status' => 1,
						'rules' => array(
							array(
								'field' => 'field_53c804aee03d7',
								'operator' => '==',
								'value' => 'Special Hours',
							),
						),
						'allorany' => 'all',
					),
					'date_format' => 'mm/dd/yy',
					'display_format' => 'mm/dd/yy',
					'first_day' => 1,
				),
				array(
					'key' => 'field_53c7e03dc7842',
					'label' => 'Monday Open',
					'name' => 'monday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e112c7849',
					'label' => 'Monday Close',
					'name' => 'monday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e08cc7843',
					'label' => 'Tuesday Open',
					'name' => 'tuesday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e126c784a',
					'label' => 'Tuesday Close',
					'name' => 'tuesday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e0a0c7844',
					'label' => 'Wednesday Open',
					'name' => 'wednesday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e131c784b',
					'label' => 'Wednesday Close',
					'name' => 'wednesday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e0cbc7845',
					'label' => 'Thursday Open',
					'name' => 'thursday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e13dc784c',
					'label' => 'Thursday Close',
					'name' => 'thursday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e0d8c7846',
					'label' => 'Friday Open',
					'name' => 'friday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e149c784d',
					'label' => 'Friday Close',
					'name' => 'friday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e0e2c7847',
					'label' => 'Saturday Open',
					'name' => 'saturday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e151c784e',
					'label' => 'Saturday Close',
					'name' => 'saturday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e0f3c7848',
					'label' => 'Sunday Open',
					'name' => 'sunday_open',
					'type' => 'text',
					'instructions' => 'Open time (military format). If not applicable, leave blank.',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array(
					'key' => 'field_53c7e15ec784f',
					'label' => 'Sunday Close',
					'name' => 'sunday_close',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
			),
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'hours',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array(
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array(
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'custom_fields',
					4 => 'discussion',
					5 => 'comments',
					6 => 'revisions',
					7 => 'slug',
					8 => 'author',
					9 => 'format',
					10 => 'featured_image',
					11 => 'categories',
					12 => 'tags',
					13 => 'send-trackbacks',
				),
			),
			'menu_order' => 0,
	));
}

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(array(
		'key' => 'group_5735ff6b185b2',
		'title' => 'Note',
		'fields' => array(
		array(
			'key' => 'field_5735ff8acd23f',
			'label' => 'Note',
			'name' => 'note',
			'type' => 'text',
			'instructions' => 'Enter text to be displayed beneath the hours text and marked by an asterisk.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		),
		'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'hours',
			),
		),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
